=== daalvand/laravel-octane/src/phpcs.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="description" type="xs:string" minOccurs="0"/>
                <xs:element name="config" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="value" type="xs:string" use="required"/>
                        <xs:attributeGroup ref="applySelectively"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="file" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="applySelectively"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="exclude-pattern" type="patternType" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element name="arg" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string"/>
                        <xs:attribute name="value" type="xs:string"/>
                        <xs:attributeGroup ref="applySelectively"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ini" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="value" type="xs:string" use="required"/>
                        <xs:attributeGroup ref="applySelectively"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="autoload" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element name="rule" type="ruleType" maxOccurs="unbounded" minOccurs="0"/>
            </xs:choice>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="namespace" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ruleType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="exclude" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attributeGroup ref="applySelectively"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="message" type="xs:string" minOccurs="0"/>
            <xs:element name="severity" minOccurs="0">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:integer">
                            <xs:attributeGroup ref="applySelectively"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="type" minOccurs="0">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="messageType">
                            <xs:attributeGroup ref="applySelectively"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="exclude-pattern" type="patternType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="include-pattern" type="patternType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="properties" type="propertiesType" minOccurs="0"/>
        </xs:choice>
        <xs:attribute name="ref" type="xs:string" use="required"/>
        <xs:attributeGroup ref="applySelectively"/>
    </xs:complexType>

    <xs:complexType name="patternType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="relative"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attributeGroup ref="applySelectively"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="propertiesType">
        <xs:sequence>
            <xs:element name="property" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="element" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                                <xs:attribute name="key" type="xs:string"/>
                                <xs:attribute name="value" type="xs:string" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="type">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="array"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="value" type="xs:string"/>
                    <xs:attribute name="extend" type="xs:boolean" default="false"/>
                    <xs:attributeGroup ref="applySelectively"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="messageType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="error"/>
            <xs:enumeration value="warning"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:attributeGroup name="applySelectively">
        <xs:attribute name="phpcs-only" type="xs:boolean" default="false"/>
        <xs:attribute name="phpcbf-only" type="xs:boolean" default="false"/>
    </xs:attributeGroup>
</xs:schema>

=== daalvand/laravel-octane/src/phpcs.xml
<?xml version="1.0"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="PHP_CodeSniffer"
         xsi:noNamespaceSchemaLocation="phpcs.xsd">
    <description>The coding standard for PHP_CodeSniffer itself.</description>

    <exclude-pattern>_ide_helper.php</exclude-pattern>
    <exclude-pattern>bootstrap/cache/*</exclude-pattern>
    <exclude-pattern>database/migrations/*</exclude-pattern>
    <exclude-pattern>storage/*</exclude-pattern>
    <exclude-pattern>vendor/*</exclude-pattern>
    <exclude-pattern>*.blade.php</exclude-pattern>
    <exclude-pattern>*.js</exclude-pattern>
    <exclude-pattern>*.css</exclude-pattern>

    <arg name="basepath" value="."/>
    <arg name="colors"/>
    <arg name="parallel" value="75"/>
    <arg value="np"/>
    <rule ref="PSR2"/>
    <rule ref="PSR1.Methods.CamelCapsMethodName.NotCamelCaps">
        <exclude-pattern>tests/*</exclude-pattern>
    </rule>

    <rule ref="PSR1.Classes.ClassDeclaration.MissingNamespace">
        <exclude-pattern>database/migrations/*</exclude-pattern>
    </rule>

    <!-- Include the whole PEAR standard -->
    <!-- <rule ref="PEAR.Commenting">-->
    <!--     <exclude name="PEAR.Commenting.ClassComment"/>-->
    <!--     <exclude name="PEAR.Commenting.FileComment.MissingCategoryTag"/>-->
    <!--     <exclude name="PEAR.Commenting.FileComment.MissingPackageTag"/>-->
    <!--     <exclude name="PEAR.Commenting.FileComment.MissingLinkTag"/>-->
    <!--     <exclude name="PEAR.Commenting.FileComment.MissingVersion"/>-->
    <!--     <exclude name="PEAR.Commenting.FileComment.Missing"/>-->
    <!--     <exclude name="PEAR.Commenting.FunctionComment.Missing"/>-->
    <!--     <exclude name="PEAR.Commenting.FunctionComment.MissingParamComment"/>-->
    <!--     <exclude name="PEAR.Commenting.FunctionComment.MissingReturn"/>-->
    <!--     <exclude name="PEAR.Commenting.InlineComment.Missing"/>-->
    <!-- </rule>-->
</ruleset>
